export const GET_DETAIL_PRODUCT_REQUEST = 'GET_DETAIL_PRODUCT_REQUEST';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';
export const GET_DETAIL_PRODUCT_FAILED = 'GET_DETAIL_PRODUCT_FAILED';
export const GET_ALL_BRAND_REQUEST = 'GET_ALL_BRAND_REQUEST';
export const GET_ALL_BRAND_SUCCESS = 'GET_ALL_BRAND_SUCCESS';
export const GET_ALL_BRAND_FAILED = 'GET_ALL_BRAND_FAILED';
export const GET_ALL_CATEGORY_REQUEST = 'GET_ALL_CATEGORY_REQUEST';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const RESET_PRODUCT_EDIT = 'RESET_PRODUCT_EDIT';
