export const GET_BRAND_LIST_REQUEST = 'GET_BRAND_LIST_REQUEST';
export const GET_BRAND_LIST_SUCCESS = 'GET_BRAND_LIST_SUCCESS';
export const GET_BRAND_LIST_FAILED = 'GET_BRAND_LIST_FAILED';

export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAILED = 'DELETE_BRAND_FAILED';
