export const GET_BRAND_REQUEST_TABLE = 'GET_BRAND_REQUEST_TABLE';
export const GET_BRAND_SUCCESS_TABLE = 'GET_BRAND_SUCCESS_TABLE';
export const GET_BRAND_FAILED_TABLE = 'GET_BRAND_FAILED_TABLE';
export const DELETE_BRAND_REQUEST = 'DELETE_BRAND_REQUEST';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAILED = 'DELETE_BRAND_FAILED';
