export const GET_ORDER_DETAIL_REQUEST = 'GET_ORDER_DETAIL_REQUEST';
export const GET_ORDER_DETAIL_SUCCESS = 'GET_ORDER_DETAIL_SUCCESS';
export const GET_ORDER_DETAIL_FAILED = 'GET_ORDER_DETAIL_FAILED';
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';

export const DELETE_ORDER_DETAIL_REQUEST = 'DELETE_ORDER_DETAIL_REQUEST';
export const DELETE_ORDER_DETAIL_SUCCESS = 'DELETE_ORDER_DETAIL_SUCCESS';
export const DELETE_ORDER_DETAIL_FAILED = 'DELETE_ORDER_DETAIL_FAILED';

export const RESET_ORDER_DETAIL = 'RESET_ORDER_DETAIL';
