export const GET_PRODUCTS_REQUEST_TABLE = 'GET_PRODUCTS_REQUEST_TABLE';
export const GET_PRODUCTS_SUCCESS_TABLE = 'GET_PRODUCTS_SUCCESS_TABLE';
export const GET_PRODUCTS_FAILED_TABLE = 'GET_PRODUCTS_FAILED_TABLE';
export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAILED = 'DELETE_PRODUCTS_FAILED';
