export const GET_USERS_REQUEST_TABLE = 'GET_USERS_REQUEST_TABLE';
export const GET_USERS_SUCCESS_TABLE = 'GET_USERS_SUCCESS_TABLE';
export const GET_USERS_FAILED_TABLE = 'GET_USERS_FAILED_TABLE';
export const DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILED = 'DELETE_USERS_FAILED';
