export const GET_DETAIL_BRAND_REQUEST = 'GET_DETAIL_BRAND_REQUEST';
export const GET_DETAIL_BRAND_SUCCESS = 'GET_DETAIL_BRAND_SUCCESS';
export const GET_DETAIL_BRAND_FAILED = 'GET_DETAIL_BRAND_FAILED';

export const UPDATE_BRAND_REQUEST = 'UPDATE_BRAND_REQUEST';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAILED = 'UPDATE_BRAND_FAILED';

export const RESET_BRAND_EDIT = 'RESET_BRAND_EDIT';
