export const GET_PRODUCTS_REVIEW_LIST_REQUEST =
  'GET_PRODUCTS_REVIEW_LIST_REQUEST';
export const GET_PRODUCTS_REVIEW_LIST_SUCCESS =
  'GET_PRODUCTS_REVIEW_LIST_SUCCESS';
export const GET_PRODUCTS_REVIEW_LIST_FAILED =
  'GET_PRODUCTS_REVIEW_LIST_FAILED';
