export const GET_PRODUCTS_REVIEW_LIST_REQUEST = 'GET_PRODUCTS_REVIEW_LIST_REQUEST';
export const GET_PRODUCTS_REVIEW_LIST_SUCCESS = 'GET_PRODUCTS_REVIEW_LIST_SUCCESS';
export const GET_PRODUCTS_REVIEW_LIST_FAILED = 'GET_PRODUCTS_REVIEW_LIST_FAILED';
export const DELETE_PRODUCTS_REVIEW_LIST_REQUEST = 'DELETE_PRODUCTS_REVIEW_LIST_REQUEST';
export const DELETE_PRODUCTS_REVIEW_LIST_SUCCESS = 'DELETE_PRODUCTS_REVIEW_LIST_SUCCESS';
export const DELETE_PRODUCTS_REVIEW_LIST_FAILED = 'DELETE_PRODUCTS_REVIEW_LIST_FAILED';
