export const GET_CATEGORY_REQUEST_TABLE = 'GET_CATEGORY_REQUEST_TABLE';
export const GET_CATEGORY_SUCCESS_TABLE = 'GET_CATEGORY_SUCCESS_TABLE';
export const GET_CATEGORY_FAILED_TABLE = 'GET_CATEGORY_FAILED_TABLE';
export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';
