export const GET_ORDERS_REQUEST_TABLE = 'GET_ORDERS_REQUEST_TABLE';
export const GET_ORDERS_SUCCESS_TABLE = 'GET_ORDERS_SUCCESS_TABLE';
export const GET_ORDERS_FAILED_TABLE = 'GET_ORDERS_FAILED_TABLE';
export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';
