export const GET_ORDERS_REQUEST_TABLE = 'GET_ORDERS_REQUEST_TABLE';
export const GET_ORDERS_SUCCESS_TABLE = 'GET_ORDERS_SUCCESS_TABLE';
export const GET_ORDERS_FAILED_TABLE = 'GET_ORDERS_FAILED_TABLE';
export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILED = 'DELETE_ORDERS_FAILED';
