export const AUTHENTICATION = 'AUTHENTICATION';

export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';

export const GET_ANALYTICS = 'GET_ANALYTICS';

export const GET_ANALYTICS_SUCCESS = 'GET_ANALYTICS_SUCCESS';
