export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS';
export const FILTER_PRODUCT_FAILED = 'FILTER_PRODUCT_FAILED';
