export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const STATUS_NO_CONTENT = 204;
